[tool.poetry]
name = "repl_python3_compilador-conchav2"
version = "0.1.0"
description = ""
authors = ["CaroObregon <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
rply = "^0.7.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
